---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Distributed Thinking Systems
description: >-
  Distributed Thinking Systems: Innovating AI, machine learning, and
  distributed computing solutions.
  <br>
  >Mostly computing on and off.
  <br>
  Using AI for good.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unixwzrd.ai"
source: "html"
show_dir_listing: false

# Strict URL configuration
strict_front_matter: true
permalink: pretty
relative_links:
  enabled: false
  collections: true

encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
timezone: America/New_York

author:
  name: "Distributed Thinking Systems"
  email: "unixwzrd@unixwzrd.ai"

# Social links
twitter_username: unixwzrd
github_username: unixwzrd
linkedin_username: unixwzrd
huggingface_username: unixwzrd
patreon_username: unixwzrd
kofi_username: unixwzrd
wandb_username: unixwzrd
discord_username: unixwzrd
medium_username: unixwzrd
youtube_username: unixwzrd
stackoverflow_username: unixwzrd
quora_username: unixwzrd
geeks_for_geeks_username: unixwzrd
reddit_username: unixwzrd
wordpress_username: unixwzrd
paypal_username: unixwzrd

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/unixwzrd"
    - platform: linkedin
      user_url: "https://linkedin.com/in/unixwzrd"
    - platform: huggingface
      user_url: "https://huggingface.co/unixwzrd"
    - platform: wandb
      user_url: "https://wandb.ai/unixwzrd"
    - platform: devdotto
      user_url: "https://dev.to/unixwzrd"
    - platform: twitter
      user_url: "https://twitter.com/unixwzrd"
    - platform: telegram
      user_url: "https://telegram.me/unixwzrd"
    - platform: bluesky
      user_url: "https://bsky.app/profile/unixwzrd.bsky.social"
    - platform: ko-fi
      user_url: "https://ko-fi.com/unixwzrd"
    - platform: patreon
      user_url: "https://patreon.com/unixwzrd"
  skin: auto

github:
  username: unixwzrd

# Codeium Public Profile
codeium_stats: https://codeium.com/profile/unixwzrd

# Pagination settings
paginate: 5  # Number of posts to show per page
paginate_path: "/page/:num/"  # URL format for paginated pages

collections:
  projects:
    output: true
    permalink: /projects/:name/
  project_posts:
    output: true
    permalink: /projects/:project_name/:title/

tagline: "Mostly computing on and off."
page_excerpts: false
excerpt_separator: "<!--more-->"

# SEO specific settings
title_separator: "|"
logo: "/assets/images/logo.png"

# Update existing social links section
social:
  name: Distributed Thinking Systems
  links:
    - https://github.com/unixwzrd
    - https://linkedin.com/in/unixwzrd
    - https://twitter.com/unixwzrd
    - https://huggingface.co/unixwzrd
    - https://wandb.ai/unixwzrd
    - https://dev.to/unixwzrd
    - https://bsky.app/profile/unixwzrd.bsky.social
    - https://ko-fi.com/unixwzrd
    - https://patreon.com/unixwzrd

# Twitter card settings
twitter:
  username: unixwzrd
  card: summary_large_image

# Update existing defaults section to include image
defaults:
  - scope:
      path: "" # Applies to all files
    values:
      layout: page
      image: /assets/images/logo.png
  - scope:
      path: ""
      type: "project_posts"
    values:
      layout: post
      image: /assets/images/logo.png

theme: jekyll-minima

header_pages:
  - about.md
  - collaborate.md
  - projects.md
  - blog.md
  - resources.md
  - contact.md
  - faq.md

google_analytics: G-QZSHSBP292

plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-paginate

exclude:
  - .DS_Store
  - .cursor/
  - .git/
  - .github/
  - .gitignore
  - .jekyll-cache/
  - .master-planning/
  - .project-core/
  - .project-planning/
  - .ruby-lsp/
  - .sass-cache/
  - .vscode/
  - Gemfile*
  - file_layout.txt
  - gemfiles/
  - html/.jekyll-cache/
  - node_modules/
  - prior-state/
  - stage/
  - tmp/
  - utils/
  - vendor/
  - docs/
